name: Auto Merge README Changes

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    paths:
      - 'README.md'

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
     contents: write
     pull-requests: write
     issues: write
     actions: write
    steps:
      - name: Automerge
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: ""
          MERGE_METHOD: "merge"
          MERGE_COMMIT_MESSAGE: "Auto-merge README changes"
          MERGE_FORKS: "true"
          MERGE_RETRIES: "6"
          MERGE_RETRY_SLEEP: "10000"
          UPDATE_LABELS: ""
          UPDATE_METHOD: "merge"